// frontend/src/lib/components/shared/corridor-editor/CorridorEditorMobile.svelte
<script lang="ts">
	// CorridorEditorMobile.svelte — Issue #1231, Slice 5: Mobile-Pendant zu
	// CorridorEditor.svelte (Desktop). Port aus
	// claude-code-handoff/current/jsx/corridor-editor-mobile.jsx.
	//
	// Reine Praesentationsschicht: importiert Daten + Logik 1:1 aus
	// corridorEditorState.ts/corridorMatch.ts (AC-15) — KEIN zweites
	// Datenmodell. Die duenne Svelte-Reaktivitaets-Verdrahtung (Save/Sync/
	// Patch) ist bewusst analog zu CorridorEditor.svelte dupliziert (Desktop
	// bleibt unangetastet) — die eigentliche Business-Logik lebt ausschliesslich
	// in corridorEditorState.ts.
	//
	// JSX-Abweichungen (Design-Referenz ist verbindlich; Begruendung im
	// Rueckmeldungstext an den Product Owner):
	//  - kein Live-Vorschau-Chips (JSX-Zeilen 160-184, 257-273, 296-299,
	//    220-225) — Desktop-Praezedenzfall (Slice 3/4) baut das ebenfalls
	//    nicht, MOCK_COMPARE_ROWS/MOCK_LOCATIONS existieren nur im JSX-Demo.
	//  - kein footer-Slot (JSX-Zeilen 245, 321) — Zustell-Controls sind seit
	//    #1232 in VersandTab.svelte, der alte Mobile-AlertsTab zeigte nur
	//    Heading+Onboarding+Tabelle (kein Footer-Inhalt vorhanden).
	//  - kein profileLabel (JSX-Zeile 245, 280) — Desktop hat kein Pendant.
	//  - CompareEndDateControlMobile (JSX-Zeilen 326-372) nicht verdrahtet —
	//    laut Spec Phase-2/Epic #29.
	//  - Warnen-Sperre fuer alarmCapable===false (Effekt-Buttons) ist NICHT im
	//    JSX enthalten, aber bindende Team-Lead-Vorgabe (Desktop-Praezedenz).
	import { getContext } from 'svelte';
	import { Eyebrow, Dot } from '$lib/components/atoms';
	import ScreenScroll from '$lib/components/mobile/ScreenScroll.svelte';
	import MBtn from '$lib/components/mobile/MBtn.svelte';
	import { api } from '$lib/api';
	import { toCompareProfile, type Trip, type SensLevel, type Corridor } from '$lib/types';
	import type { SaveStatus } from '$lib/stores/saveStatusStore.svelte';
	import type { CompareWizardState } from '$lib/components/compare/compareWizardState.svelte';
	import type { ProfileKey } from '$lib/components/compare/compareMetricDefs';
	import { corridorFmt } from './corridorMatch.ts';
	import {
		buildRoutePool, addRow, removeRow, patchRow, validateCorridorRows,
		buildCorridorSavePayload, ROUTE_CTX_DEFAULTS, valueAtPointer, clampDragValue, clampBoundInput,
		saveGateDecision, openBoundValue, type CorridorRowState,
		COMPARE_METRIC_DEFS, buildComparePool, addCompareRow, VERGLEICH_CTX_DEFAULTS,
		buildCompareCorridorSavePayload, buildComparePrefillRows,
		type RouteMetricDef, type CompareMetricDef,
	} from './corridorEditorState.ts';

	interface Props {
		context?: 'route' | 'vergleich';
		trip?: Trip;
		onTripUpdate?: (t: Trip) => void;
		saveController?: SaveStatus;
	}
	let { context = 'route', trip, onTripUpdate, saveController }: Props = $props();

	const ws = context === 'vergleich' ? getContext<CompareWizardState>('compare-wizard-state') : undefined;

	// AC-10: "zuletzt bekannte Stufe" bezieht sich auf den beim Mount geladenen
	// Stand — analog Desktop (CorridorEditor.svelte), gilt fuer beide Kontexte.
	const originalLevels = (
		context === 'vergleich'
			? (ws?.metricAlertLevels as Record<string, SensLevel> | undefined)
			: trip?.display_config?.metric_alert_levels
	) ?? {} as Record<string, SensLevel>;
	const originalActiveMetricKeys: string[] = context === 'vergleich' ? [...(ws?.activeMetricKeys ?? [])] : [];

	const isFreshCompareCreate = context === 'vergleich' && !ws?.isEditMode && (ws?.corridors ?? []).length === 0;
	function computeInitialCompare(): { rows: CorridorRowState[]; poolLeft: CompareMetricDef[]; unknownCorridors: Corridor[] } {
		if (!isFreshCompareCreate) return buildComparePool(ws?.corridors ?? []);
		const profileKey = ws?.activityProfile ? (toCompareProfile(ws.activityProfile) as ProfileKey) : 'ALLGEMEIN';
		const prefillRows = buildComparePrefillRows(profileKey);
		const poolLeft = COMPARE_METRIC_DEFS.filter((d) => !prefillRows.some((r) => r.metric === d.metric));
		return { rows: prefillRows, poolLeft, unknownCorridors: [] };
	}
	const initial = context === 'vergleich' ? computeInitialCompare() : { ...buildRoutePool(trip?.corridors ?? []), unknownCorridors: [] };
	let rows = $state<CorridorRowState[]>(initial.rows);
	let poolLeft = $state<(RouteMetricDef | CompareMetricDef)[]>(initial.poolLeft);
	const unknownCorridors: Corridor[] = initial.unknownCorridors;
	let removedMetrics = $state<string[]>([]);

	const validation = $derived(validateCorridorRows(rows));
	const notifyN = $derived(rows.filter((r) => r.notify).length);
	const markN = $derived(rows.filter((r) => r.mark).length);

	function buildSaveFn() {
		const payload = buildCorridorSavePayload(rows, originalLevels, removedMetrics);
		return async () => {
			const updated = await api.put<Trip>(`/api/trips/${trip!.id}`, {
				corridors: payload.corridors,
				display_config: { ...trip!.display_config, metric_alert_levels: payload.metric_alert_levels },
			});
			onTripUpdate?.(updated);
		};
	}
	function syncToWizard() {
		if (!ws) return;
		const payload = buildCompareCorridorSavePayload(rows, removedMetrics, {
			idealRanges: ws.idealRanges,
			activeMetricKeys: ws.activeMetricKeys,
			metricAlertLevels: ws.metricAlertLevels as Record<string, SensLevel | undefined>,
		}, unknownCorridors);
		ws.corridors = payload.corridors;
		ws.idealRanges = payload.idealRanges;
		ws.activeMetricKeys = payload.activeMetricKeys;
		ws.metricAlertLevels = payload.metricAlertLevels;
	}
	if (isFreshCompareCreate && rows.length > 0) syncToWizard();

	function maybeSchedule() {
		if (context === 'vergleich') {
			if (saveGateDecision(rows) === 'schedule') syncToWizard();
			return;
		}
		if (saveGateDecision(rows) === 'schedule') saveController?.schedule(buildSaveFn());
		else saveController?.setDirty();
	}
	function patch(metric: string, p: Partial<Pick<CorridorRowState, 'min' | 'max' | 'notify' | 'mark'>>) {
		rows = patchRow(rows, metric, p);
		maybeSchedule();
	}
	function patchBound(row: CorridorRowState, side: 'min' | 'max', value: number | null) {
		patch(row.metric, side === 'min' ? { min: value } : { max: value });
	}
	function remove(metric: string) {
		rows = removeRow(rows, metric);
		removedMetrics = [...removedMetrics, metric];
		maybeSchedule();
	}
	function add(metric: string) {
		const next = context === 'vergleich'
			? addCompareRow(rows, poolLeft as CompareMetricDef[], metric, VERGLEICH_CTX_DEFAULTS, originalActiveMetricKeys.includes(metric))
			: addRow(rows, poolLeft as RouteMetricDef[], metric, ROUTE_CTX_DEFAULTS);
		rows = next.rows;
		poolLeft = next.poolLeft;
		maybeSchedule();
	}

	// Touch-Band: dual-handle Pointer-Drag (JSX-Zeilen 17-82) — setPointerCapture
	// fuer stabile Touch-Gesten, Wertelogik in valueAtPointer/clampDragValue.
	let dragging = $state<{ metric: string; side: 'min' | 'max'; track: HTMLElement } | null>(null);
	function onHandleDown(e: PointerEvent, metric: string, side: 'min' | 'max') {
		(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);
		const track = (e.currentTarget as HTMLElement).closest('.cem-band-track') as HTMLElement | null;
		if (track) dragging = { metric, side, track };
	}
	function onWindowPointerMove(e: PointerEvent) {
		if (!dragging) return;
		const row = rows.find((r) => r.metric === dragging!.metric);
		if (!row) return;
		const rect = dragging.track.getBoundingClientRect();
		const raw = valueAtPointer(e.clientX, rect.left, rect.width, row.scale, row.step);
		const value = clampDragValue(dragging.side, raw, row.min, row.max);
		patchBound(row, dragging.side, value);
	}
	function onWindowPointerUp() {
		dragging = null;
	}

	// Stepper (CM_Bound, JSX-Zeilen 85-132): +/- je Grenze statt Zahlen-Tastatur.
	function fallbackFor(row: CorridorRowState, side: 'min' | 'max'): number {
		const [lo, hi] = row.scale;
		return side === 'min' ? lo + (hi - lo) * 0.25 : lo + (hi - lo) * 0.75;
	}
	function nudge(row: CorridorRowState, side: 'min' | 'max', dir: 1 | -1) {
		const current = side === 'min' ? row.min : row.max;
		const base = current ?? fallbackFor(row, side);
		const next = Math.round((base + dir * row.step) / row.step) * row.step;
		const clamped = Math.max(row.scale[0], Math.min(row.scale[1], next));
		patchBound(row, side, clampBoundInput(clamped, side, row));
	}
	function openBound(row: CorridorRowState, side: 'min' | 'max') {
		patchBound(row, side, openBoundValue(row, side));
	}
	function rangeLabel(row: CorridorRowState): string {
		if (row.kind === 'ordinal') {
			const lbl = (i: number | null) => (i == null ? null : (row.ordinalLabels?.[i] ?? String(i)));
			if (row.min != null && row.max != null) return `${lbl(row.min)} … ${lbl(row.max)}`;
			if (row.min != null) return `≥ ${lbl(row.min)}`;
			if (row.max != null) return `≤ ${lbl(row.max)}`;
			return 'offen';
		}
		if (row.min != null && row.max != null) return `${corridorFmt(row.min, '')} … ${corridorFmt(row.max, row.unit)}`;
		if (row.min != null) return `≥ ${corridorFmt(row.min, row.unit)}`;
		if (row.max != null) return `≤ ${corridorFmt(row.max, row.unit)}`;
		return 'offen';
	}
</script>

<svelte:window onpointermove={onWindowPointerMove} onpointerup={onWindowPointerUp} />

<ScreenScroll padding={14}>
	<div class="cem" data-testid="corridor-editor-mobile-{context}">
		{#if context === 'vergleich'}
			<Eyebrow>Wertebereiche · Idealbereiche</Eyebrow>
			<div class="cem-title">Sag mir, welche Werte dir ideal sind</div>
			<div class="cem-lead">Ein Wertebereich je Metrik legt deinen Idealbereich fest. Werte im Bereich werden im Briefing pro Ort grün markiert — kein Score, kein Ranking, nur eine Lese-Hilfe.</div>
		{:else}
			<Eyebrow>Wertebereiche · Warn-Schwellen</Eyebrow>
			<div class="cem-title">Sag mir, wenn das Wetter aus dem Rahmen läuft</div>
			<div class="cem-lead">Ein Wertebereich je Metrik legt fest, welche Werte du auf der Tour noch akzeptierst. Verlässt ein Wert den Bereich, bekommst du zwischen den Briefings eine Sofort-Meldung.</div>
		{/if}

		<div class="cem-legend">
			<span><span class="cem-swatch mark"></span> im Bereich = <strong class="cem-good">markiert</strong></span>
			<span><span class="cem-swatch warn"></span> außerhalb = <strong class="cem-warn">Warnung</strong></span>
		</div>

		{#if !validation.valid}
			<p class="cem-error" role="alert" data-testid="corridor-editor-mobile-error">
				Mindestens eine Grenze (Von oder Bis) ist Pflicht: {validation.errors.join(', ')}
			</p>
		{/if}

		{#each rows as row (row.metric)}
			{@const span = row.scale[1] - row.scale[0] || 1}
			{@const leftPct = row.min == null ? 0 : Math.max(0, Math.min(1, (row.min - row.scale[0]) / span)) * 100}
			{@const rightPct = row.max == null ? 100 : Math.max(0, Math.min(1, (row.max - row.scale[0]) / span)) * 100}
			<div class="cem-card" data-testid="corridor-mobile-row-{row.metric}">
				<div class="cem-head">
					<div>
						<span class="cem-label">{row.label}</span>
						<span class="cem-unit">{row.unit}</span>
					</div>
					<span class="cem-range">{rangeLabel(row)}</span>
				</div>
				{#if row.note}<div class="cem-note">{row.note}</div>{/if}

				<div class="cem-band-track" data-testid="corridor-mobile-band-{row.metric}">
					<div class="cem-band-fill" class:mark={row.mark} style="left:{leftPct}%;width:{rightPct - leftPct}%"></div>
					{#if row.min == null}<span class="cem-open cem-open-left">◂ offen</span>{/if}
					{#if row.max == null}<span class="cem-open cem-open-right">offen ▸</span>{/if}
					{#if row.min != null}
						<div class="cem-handle" style="left:{leftPct}%" onpointerdown={(e) => onHandleDown(e, row.metric, 'min')}></div>
					{/if}
					{#if row.max != null}
						<div class="cem-handle" class:mark={row.mark} style="left:{rightPct}%" onpointerdown={(e) => onHandleDown(e, row.metric, 'max')}></div>
					{/if}
				</div>
				<div class="cem-band-scale">
					<span>{corridorFmt(row.scale[0], '')}</span><span>{corridorFmt(row.scale[1], '')}</span>
				</div>

				<div class="cem-bounds">
					{#each ['min', 'max'] as const as side}
						{@const value = side === 'min' ? row.min : row.max}
						<div class="cem-bound">
							<div class="cem-bound-label">{side === 'min' ? 'Von' : 'Bis'}</div>
							{#if value == null}
								<button type="button" class="cem-open-btn" onclick={() => openBound(row, side)}>offen · + Grenze</button>
							{:else if row.kind === 'ordinal'}
								<div class="cem-ordinal-group" data-testid="corridor-mobile-ordinal-{side}-{row.metric}">
									{#each row.ordinalLabels ?? [] as lbl, idx (lbl)}
										<button type="button" class="cem-ordinal-btn" class:on={value === idx} onclick={() => patchBound(row, side, clampBoundInput(idx, side, row))}>{lbl}</button>
									{/each}
									<button type="button" class="cem-clear-btn" title="Grenze öffnen" onclick={() => patchBound(row, side, null)}>×</button>
								</div>
							{:else}
								<!-- AC-14 vs. JSX-Optik (Tech-Lead-Entscheidung): Hit-Area-Technik —
								     .cem-step-btn selbst ist 44x44 (getBoundingClientRect-pflichtig),
								     .cem-step-btn-glyph bleibt die 40px-JSX-Optik (Z. 100-105) innen zentriert. -->
								<div class="cem-stepper">
									<button type="button" class="cem-step-btn" onclick={() => nudge(row, side, -1)}><span class="cem-step-btn-glyph">−</span></button>
									<div class="cem-step-value">
										<div class="cem-step-num">{value}</div>
										<div class="cem-step-unit">{row.unit}</div>
									</div>
									<button type="button" class="cem-step-btn" onclick={() => nudge(row, side, 1)}><span class="cem-step-btn-glyph">+</span></button>
									<button type="button" class="cem-clear-btn" title="Grenze öffnen" onclick={() => patchBound(row, side, null)}>×</button>
								</div>
							{/if}
						</div>
					{/each}
				</div>

				<div class="cem-effects">
					{#if row.alarmCapable === false}
						<button type="button" class="cem-effect notify disabled" disabled title="nur Markieren – für diese Metrik gibt es keinen Alarm-Abgleich">Warnen</button>
					{:else}
						<button type="button" class="cem-effect notify" class:on={row.notify} aria-pressed={row.notify} onclick={() => patch(row.metric, { notify: !row.notify })}>Warnen</button>
					{/if}
					<button type="button" class="cem-effect mark" class:on={row.mark} aria-pressed={row.mark} onclick={() => patch(row.metric, { mark: !row.mark })}>Markieren</button>
				</div>

				<div class="cem-remove-row">
					<button type="button" class="cem-remove" onclick={() => remove(row.metric)}>✕ entfernen</button>
				</div>
			</div>
		{/each}

		{#if poolLeft.length > 0}
			<div class="cem-pool">
				<div class="cem-pool-label">Metrik hinzufügen</div>
				{#each poolLeft as m (m.metric)}
					<MBtn block variant="ghost" size="lg" onclick={() => add(m.metric)}>＋ {m.label}</MBtn>
				{/each}
			</div>
		{/if}

		<div class="cem-summary">
			<span class="cem-summary-item"><Dot tone="warn" /> {notifyN} × Warnen</span>
			<span class="cem-summary-item"><Dot tone="good" /> {markN} × Markieren</span>
		</div>
		{#if context === 'vergleich'}
			<div class="cem-neutral" data-testid="corridor-editor-mobile-neutral-hint">kein Score · kein Rang · Wertebereiche markieren nur, sie sortieren nicht</div>
			{#if unknownCorridors.length > 0}
				<div class="cem-neutral" data-testid="corridor-editor-mobile-unknown-hint">
					{unknownCorridors.length} weitere{unknownCorridors.length === 1 ? 'r Eintrag bleibt' : ' Einträge bleiben'} erhalten
				</div>
			{/if}
		{/if}
	</div>
</ScreenScroll>

<style>
	.cem { font-family: var(--g-font-sans); }
	.cem-title { font-size: 19px; font-weight: 600; letter-spacing: -0.01em; line-height: 1.2; margin: 6px 0; color: var(--g-ink); }
	.cem-lead { font-size: 13px; color: var(--g-ink-2); line-height: 1.5; margin-bottom: 14px; }
	.cem-legend { display: flex; flex-direction: column; gap: 8px; padding: 12px 14px; margin-bottom: 14px; background: var(--g-card-alt); border: 1px solid var(--g-rule-soft); border-radius: var(--g-r-3, 10px); font-size: 12.5px; color: var(--g-ink-2); }
	.cem-swatch { width: 22px; height: 8px; border-radius: 4px; display: inline-block; vertical-align: middle; margin-right: 6px; }
	.cem-swatch.mark { background: var(--g-good); opacity: 0.85; }
	.cem-swatch.warn { background: rgba(192, 138, 26, 0.28); }
	.cem-good { color: var(--g-good); }
	.cem-warn { color: #8a6210; }
	.cem-error { color: #8a6210; background: rgba(192, 138, 26, 0.12); border: 1px solid rgba(192, 138, 26, 0.35); border-radius: var(--g-r-2, 6px); padding: 8px 12px; font-size: 13px; margin-bottom: 12px; }
	.cem-card { background: var(--g-card); border: 1px solid var(--g-rule); border-radius: var(--g-r-3, 10px); padding: 14px 14px 12px; margin-bottom: 10px; }
	.cem-head { display: flex; align-items: baseline; justify-content: space-between; gap: 8px; }
	.cem-label { font-size: 15px; font-weight: 600; color: var(--g-ink); }
	.cem-unit { font-size: 10px; color: var(--g-ink-4); margin-left: 6px; }
	.cem-range { font-size: 13px; font-weight: 600; color: var(--g-ink); white-space: nowrap; }
	.cem-note { font-size: 11.5px; color: var(--g-ink-4); margin-top: 2px; font-style: italic; }
	.cem-band-track { position: relative; height: 14px; margin-top: 22px; margin-bottom: 8px; border-radius: 7px; background: var(--g-rule-soft); }
	.cem-band-fill { position: absolute; top: 0; bottom: 0; border-radius: 7px; background: var(--g-ink-3); opacity: 0.4; }
	.cem-band-fill.mark { background: var(--g-good); opacity: 0.85; }
	.cem-handle { position: absolute; top: 50%; width: 24px; height: 24px; margin-left: -12px; margin-top: -12px; border-radius: 50%; background: #fff; border: 2px solid var(--g-accent); cursor: ew-resize; touch-action: none; z-index: 3; }
	.cem-handle.mark { border-color: var(--g-good); }
	/* AC-14 Hit-Area-Technik (Tech-Lead-Entscheidung, kein Playwright-Pflichtziel
	   fuer den Handle selbst — AC-14-Test erfasst nur Stepper/Toggle-Buttons):
	   unsichtbare 44x44-Trefffläche um den 24px-Punkt, Optik bleibt JSX-treu. */
	.cem-handle::before { content: ''; position: absolute; top: 50%; left: 50%; width: 44px; height: 44px; transform: translate(-50%, -50%); }
	.cem-open { position: absolute; top: -18px; font-size: 10px; color: var(--g-ink-4); }
	.cem-open-left { left: 2px; }
	.cem-open-right { right: 2px; }
	.cem-band-scale { display: flex; justify-content: space-between; font-size: 10px; color: var(--g-ink-4); }
	.cem-bounds { display: flex; gap: 12px; margin-top: 12px; }
	.cem-bound { flex: 1; min-width: 0; }
	.cem-bound-label { font-size: 9.5px; color: var(--g-ink-4); letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 5px; }
	.cem-open-btn { width: 100%; min-height: 44px; border: 1px dashed var(--g-rule); background: transparent; border-radius: var(--g-r-2, 6px); cursor: pointer; color: var(--g-ink-4); font-size: 12px; }
	.cem-stepper, .cem-ordinal-group { display: flex; align-items: center; gap: 6px; }
	/* AC-14 Hit-Area-Technik: Trefffläche 44x44 (Playwright-messbar), Glyph-Optik bleibt 40px wie im JSX. */
	.cem-step-btn { width: 44px; height: 44px; flex-shrink: 0; display: inline-flex; align-items: center; justify-content: center; border: none; background: transparent; padding: 0; cursor: pointer; }
	.cem-step-btn-glyph { display: inline-flex; align-items: center; justify-content: center; width: 40px; height: 40px; border: 1px solid var(--g-rule); background: var(--g-card); border-radius: var(--g-r-2, 6px); color: var(--g-ink); font-size: 20px; line-height: 1; }
	.cem-step-value { flex: 1; min-width: 0; text-align: center; padding: 0 2px; }
	.cem-step-num { font-size: 16px; font-weight: 600; color: var(--g-ink); font-variant-numeric: tabular-nums; line-height: 1.1; }
	.cem-step-unit { font-size: 9px; color: var(--g-ink-4); }
	.cem-ordinal-btn { flex: 1; min-height: 44px; padding: 4px 6px; font-size: 11.5px; border-radius: var(--g-r-2, 6px); border: 1px solid var(--g-rule); background: transparent; color: var(--g-ink-3); cursor: pointer; }
	.cem-ordinal-btn.on { border-color: var(--g-accent); color: var(--g-accent-deep); background: var(--g-accent-tint); }
	.cem-clear-btn { width: 30px; height: 40px; flex-shrink: 0; border: none; background: transparent; cursor: pointer; color: var(--g-ink-4); font-size: 15px; }
	.cem-effects { display: flex; gap: 8px; margin-top: 12px; }
	.cem-effect { flex: 1; display: inline-flex; align-items: center; justify-content: center; gap: 8px; min-height: 44px; padding: 0 12px; border-radius: var(--g-r-3, 10px); cursor: pointer; font-size: 14px; font-weight: 600; background: transparent; color: var(--g-ink-4); border: 1px solid var(--g-rule); }
	.cem-effect.notify.on { color: var(--g-warn, #8a6210); border-color: var(--g-warn, #8a6210); background: rgba(192, 138, 26, 0.12); }
	.cem-effect.mark.on { color: var(--g-good); border-color: var(--g-good); background: rgba(61, 107, 58, 0.12); }
	.cem-effect.disabled { opacity: 0.4; cursor: not-allowed; }
	.cem-remove-row { display: flex; justify-content: flex-end; margin-top: 8px; }
	.cem-remove { background: transparent; border: none; padding: 6px 2px; color: var(--g-ink-4); cursor: pointer; font-size: 11.5px; }
	.cem-pool { display: flex; flex-direction: column; gap: 8px; margin: 4px 0 6px; }
	.cem-pool-label { font-size: 10px; color: var(--g-ink-4); letter-spacing: 0.08em; text-transform: uppercase; }
	.cem-summary { display: flex; align-items: center; gap: 16px; flex-wrap: wrap; margin-top: 10px; font-size: 12.5px; color: var(--g-ink-2); }
	.cem-summary-item { display: inline-flex; align-items: center; gap: 7px; }
	.cem-neutral { font-size: 10.5px; color: var(--g-ink-4); margin-top: 8px; letter-spacing: 0.02em; line-height: 1.5; }
</style>

// claude-code-handoff/current/jsx/corridor-editor-mobile.jsx
/* ════════════════════════════════════════════════════════════════════════
 *  corridor-editor-mobile.jsx  —  Mobile-Spiegel des Korridor-Editors (375 px)
 * ════════════════════════════════════════════════════════════════════════
 *
 *  Desktop-Pendant: corridor-editor.jsx (CorridorEditor). Diese Datei ist
 *  KEIN Fork — Daten + Match-Logik kommen aus dem Desktop-Organism:
 *      corridorInside · corridorFmt · CORRIDOR_CTX · CORRIDOR_SEED · CORRIDOR_POOL
 *  Nur das Layout ist mobil neu: eine Card je Metrik statt Tabellen-Grid,
 *  Touch ≥ 44 px, Stepper statt Mini-Number-Inputs, 16 px Eingaben.
 *
 *  Prefix CM_ (Babel-Scope-Disziplin, CLAUDE.md · M* wäre Mobile-Atom-Namespace,
 *  daher CM_ für Compare/Corridor-Mobile-Helfer). Nutzt mobile-shell (MBtn,
 *  ScreenScroll) + Atoms (Eyebrow, Dot).
 *  Export: window.CorridorEditorMobile · window.CompareEndDateControlMobile
 * ──────────────────────────────────────────────────────────────────────── */

/* ─── Touch-Band: dual-handle mit offenen Enden (mobile-eigene Geometrie) ─── */
function CM_Band({ scale, step, min, max, notify, mark, onChange }) {
  const trackRef = React.useRef(null);
  const [drag, setDrag] = React.useState(null);
  const [lo, hi] = scale;
  const span = hi - lo || 1;
  const pos = (v) => Math.max(0, Math.min(1, (v - lo) / span));
  const valAt = (clientX) => {
    const el = trackRef.current;
    if (!el) return lo;
    const r = el.getBoundingClientRect();
    const t = Math.max(0, Math.min(1, (clientX - r.left) / (r.width || 1)));
    return Math.round((lo + t * span) / step) * step;
  };

  React.useEffect(() => {
    if (!drag) return;
    const move = (e) => {
      const cx = e.touches ? e.touches[0].clientX : e.clientX;
      let v = valAt(cx);
      if (drag === "min") { if (max != null) v = Math.min(v, max); onChange({ min: v }); }
      else                { if (min != null) v = Math.max(v, min); onChange({ max: v }); }
    };
    const up = () => setDrag(null);
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up);
    return () => { window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); };
  }, [drag, min, max]);

  const left  = min != null ? pos(min) : 0;
  const right = max != null ? pos(max) : 1;
  const fill  = mark ? "var(--g-good)" : "var(--g-ink-3)";
  const outsideTint = notify ? "rgba(192,138,26,0.16)" : "transparent";

  const Handle = ({ side, value }) => (
    <div onPointerDown={(e) => { e.currentTarget.setPointerCapture?.(e.pointerId); setDrag(side); }}
      style={{
        position: "absolute", top: "50%", left: `${pos(value) * 100}%`,
        width: 24, height: 24, marginLeft: -12, marginTop: -12, borderRadius: "50%",
        background: "#fff", border: `2px solid ${mark ? "var(--g-good)" : "var(--g-accent)"}`,
        boxShadow: "var(--g-shadow-1)", cursor: "ew-resize", touchAction: "none", zIndex: 3,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}>
      <span style={{ width: 6, height: 6, borderRadius: "50%", background: mark ? "var(--g-good)" : "var(--g-accent)" }}/>
    </div>
  );

  return (
    <div>
      <div ref={trackRef} style={{ position: "relative", height: 14, marginTop: 22, marginBottom: 8 }}>
        <div style={{ position: "absolute", inset: 0, borderRadius: 7, background: "var(--g-rule-soft)", overflow: "hidden" }}>
          {min != null && <div style={{ position: "absolute", top: 0, bottom: 0, left: 0, width: `${left * 100}%`, background: outsideTint }}/>}
          {max != null && <div style={{ position: "absolute", top: 0, bottom: 0, right: 0, width: `${(1 - right) * 100}%`, background: outsideTint }}/>}
        </div>
        <div style={{ position: "absolute", top: 0, bottom: 0, left: `${left * 100}%`, width: `${(right - left) * 100}%`, background: fill, opacity: mark ? 0.85 : 0.4, borderRadius: 7 }}/>
        {min == null && <span className="mono" style={{ position: "absolute", left: 2, top: -18, fontSize: 10, color: "var(--g-ink-4)" }}>◂ offen</span>}
        {max == null && <span className="mono" style={{ position: "absolute", right: 2, top: -18, fontSize: 10, color: "var(--g-ink-4)" }}>offen ▸</span>}
        {min != null && <Handle side="min" value={min}/>}
        {max != null && <Handle side="max" value={max}/>}
      </div>
      <div className="mono" style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "var(--g-ink-4)" }}>
        <span>{corridorFmt(lo, "")}</span><span>{corridorFmt(hi, "")}</span>
      </div>
    </div>
  );
}

/* ─── Touch-Grenze: Stepper (−/+) statt Tastatur-Input ─── */
function CM_Bound({ side, value, unit, scale, step, min, max, onChange }) {
  const label = side === "min" ? "Von" : "Bis";
  const open = value == null;
  const [lo, hi] = scale;
  const fallback = side === "min" ? lo + (hi - lo) * 0.25 : lo + (hi - lo) * 0.75;
  const clampV = (v) => {
    v = Math.round(v / step) * step;
    v = Math.max(lo, Math.min(hi, v));
    if (side === "min" && max != null) v = Math.min(v, max);
    if (side === "max" && min != null) v = Math.max(v, min);
    return v;
  };
  const nudge = (d) => onChange(clampV((value ?? fallback) + d * step));

  const StepBtn = ({ children, onTap }) => (
    <button onClick={onTap} style={{
      width: 40, height: 40, flexShrink: 0, border: "1px solid var(--g-rule)", background: "var(--g-card)",
      borderRadius: "var(--g-r-2)", cursor: "pointer", color: "var(--g-ink)", fontSize: 20, lineHeight: 1,
      display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--g-font-mono)",
    }}>{children}</button>
  );

  return (
    <div style={{ flex: 1, minWidth: 0 }}>
      <div className="mono" style={{ fontSize: 9.5, color: "var(--g-ink-4)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 5 }}>{label}</div>
      {open ? (
        <button onClick={() => onChange(clampV(fallback))} style={{
          width: "100%", minHeight: 40, border: "1px dashed var(--g-rule)", background: "transparent",
          borderRadius: "var(--g-r-2)", cursor: "pointer", color: "var(--g-ink-4)",
          fontFamily: "var(--g-font-mono)", fontSize: 12, letterSpacing: "0.02em",
        }}>offen · + Grenze</button>
      ) : (
        <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
          <StepBtn onTap={() => nudge(-1)}>−</StepBtn>
          <div style={{ flex: 1, minWidth: 0, textAlign: "center", padding: "0 2px" }}>
            <div className="mono" style={{ fontSize: 16, fontWeight: 600, color: "var(--g-ink)", fontVariantNumeric: "tabular-nums", lineHeight: 1.1 }}>{value}</div>
            <div className="mono" style={{ fontSize: 9, color: "var(--g-ink-4)" }}>{unit}</div>
          </div>
          <StepBtn onTap={() => nudge(1)}>+</StepBtn>
          <button title="Grenze öffnen" onClick={() => onChange(null)} style={{
            width: 30, height: 40, border: "none", background: "transparent", cursor: "pointer",
            color: "var(--g-ink-4)", fontSize: 15,
          }}>×</button>
        </div>
      )}
    </div>
  );
}

/* ─── Wirkungs-Toggle (Touch, ≥ 44 px) ─── */
function CM_Effect({ kind, on, onToggle }) {
  const conf = kind === "notify"
    ? { label: "Warnen", tone: "var(--g-warn)", tint: "rgba(192,138,26,0.12)", fg: "#8a6210" }
    : { label: "Markieren", tone: "var(--g-good)", tint: "rgba(61,107,58,0.12)", fg: "var(--g-good)" };
  return (
    <button onClick={onToggle} aria-pressed={on} style={{
      flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8,
      minHeight: 44, padding: "0 12px", borderRadius: "var(--g-r-3)", cursor: "pointer",
      fontFamily: "var(--g-font-sans)", fontSize: 14, fontWeight: 600,
      background: on ? conf.tint : "transparent",
      color: on ? conf.fg : "var(--g-ink-4)",
      border: `1px solid ${on ? conf.tone : "var(--g-rule)"}`,
    }}>
      <span style={{
        width: 16, height: 16, flexShrink: 0, borderRadius: kind === "notify" ? 3 : "50%",
        background: on ? conf.tone : "transparent", border: on ? "none" : "1.5px solid var(--g-rule)",
        display: "inline-flex", alignItems: "center", justifyContent: "center",
      }}>
        {on && <svg width="9" height="9" viewBox="0 0 12 12" fill="none" stroke="#fff" strokeWidth="2.4"><path d="M2 6l3 3 5-6"/></svg>}
      </span>
      {conf.label}
    </button>
  );
}

/* ─── Live-Vorschau-Chips (Orte/Etappen · grün wenn im Korridor) ─── */
function CM_PreviewChips({ subjects, unit }) {
  if (!subjects || subjects.length === 0) return null;
  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
      {subjects.map((s, i) => {
        const st = s.inside;
        const bg = st === true ? "rgba(61,107,58,0.10)" : st === false ? "rgba(192,138,26,0.10)" : "var(--g-card-alt)";
        const fg = st === true ? "var(--g-good)" : st === false ? "#8a6210" : "var(--g-ink-3)";
        const bd = st === true ? "rgba(61,107,58,0.35)" : st === false ? "rgba(192,138,26,0.35)" : "var(--g-rule-soft)";
        return (
          <span key={i} className="mono" style={{
            display: "inline-flex", alignItems: "center", gap: 5, padding: "4px 9px", borderRadius: "var(--g-r-pill)",
            background: bg, color: fg, border: `1px solid ${bd}`, fontSize: 11, fontVariantNumeric: "tabular-nums",
          }}>
            <span style={{ color: "var(--g-ink-4)" }}>{s.label}</span>
            <strong style={{ fontWeight: 600 }}>{corridorFmt(s.value, unit)}</strong>
            {st === true && <span aria-hidden>✓</span>}
            {st === false && <span aria-hidden>▲</span>}
          </span>
        );
      })}
    </div>
  );
}

/* ─── Eine Korridor-Card ─── */
function CM_Card({ metric, subjects, onChange, onRemove }) {
  const { unit, scale, step, min, max, notify, mark } = metric;
  return (
    <div style={{ background: "var(--g-card)", border: "1px solid var(--g-rule)", borderRadius: "var(--g-r-3)", padding: "14px 14px 12px", marginBottom: 10 }}>
      {/* Kopf: Metrik + Bereich */}
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 8 }}>
        <div style={{ minWidth: 0 }}>
          <span style={{ fontSize: 15, fontWeight: 600, color: "var(--g-ink)" }}>{metric.label}</span>
          <span className="mono" style={{ fontSize: 10, color: "var(--g-ink-4)", marginLeft: 6 }}>{unit}</span>
        </div>
        <span className="mono" style={{ fontSize: 13, fontWeight: 600, color: "var(--g-ink)", fontVariantNumeric: "tabular-nums", whiteSpace: "nowrap" }}>
          {KE_rangeLabelMobile(min, max, unit)}
        </span>
      </div>
      {metric.note && <div style={{ fontSize: 11.5, color: "var(--g-ink-4)", marginTop: 2, fontStyle: "italic" }}>{metric.note}</div>}

      {/* Band */}
      <div style={{ marginTop: 4 }}>
        <CM_Band scale={scale} step={step} min={min} max={max} notify={notify} mark={mark} onChange={(patch) => onChange(patch)}/>
      </div>

      {/* Grenzen-Stepper */}
      <div style={{ display: "flex", gap: 12, marginTop: 12 }}>
        <CM_Bound side="min" value={min} unit={unit} scale={scale} step={step} min={min} max={max} onChange={(v) => onChange({ min: v })}/>
        <CM_Bound side="max" value={max} unit={unit} scale={scale} step={step} min={min} max={max} onChange={(v) => onChange({ max: v })}/>
      </div>

      {/* Wirkungen */}
      <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
        <CM_Effect kind="notify" on={notify} onToggle={() => onChange({ notify: !notify })}/>
        <CM_Effect kind="mark"   on={mark}   onToggle={() => onChange({ mark: !mark })}/>
      </div>

      {/* Vorschau */}
      {subjects && subjects.length > 0 && (
        <div style={{ marginTop: 12, paddingTop: 12, borderTop: "1px solid var(--g-rule-soft)" }}>
          <CM_PreviewChips subjects={subjects} unit={unit}/>
        </div>
      )}

      {/* Entfernen */}
      <div style={{ display: "flex", justifyContent: "flex-end", marginTop: 8 }}>
        <button onClick={onRemove} style={{ background: "transparent", border: "none", padding: "6px 2px", color: "var(--g-ink-4)", cursor: "pointer", fontSize: 11.5, fontFamily: "var(--g-font-mono)", letterSpacing: "0.04em" }}>✕ entfernen</button>
      </div>
    </div>
  );
}

/* Mobile-Bereichslabel (kompakt · nutzt corridorFmt für Vorzeichen). */
function KE_rangeLabelMobile(min, max, unit) {
  const f = (v) => corridorFmt(v, unit);
  if (min != null && max != null) return `${corridorFmt(min, "")} … ${f(max)}`;
  if (min != null) return `≥ ${f(min)}`;
  if (max != null) return `≤ ${f(max)}`;
  return "offen";
}

/* ════════════════════ CorridorEditorMobile — DER Mobile-Organism ════════════════════ */
function CorridorEditorMobile({ context = "route", profileLabel, footer }) {
  const ctx = (window.CORRIDOR_CTX || {})[context] || {};
  const seed = (window.CORRIDOR_SEED || {})[context] || [];
  const pool = (window.CORRIDOR_POOL || {})[context] || [];

  const [rows, setRows] = React.useState(() => seed.map(m => ({ ...m, notify: ctx.defaultNotify, mark: ctx.defaultMark })));
  const [poolLeft, setPoolLeft] = React.useState(pool);

  const patchRow = (id, patch) => setRows(rs => rs.map(r => r.id === id ? { ...r, ...patch } : r));
  const removeRow = (id) => setRows(rs => rs.filter(r => r.id !== id));
  const addRow = (m) => { setRows(rs => [...rs, { ...m, notify: ctx.defaultNotify, mark: ctx.defaultMark }]); setPoolLeft(p => p.filter(x => x.id !== m.id)); };

  /* Subjekte je Zeile (Live-Vorschau, C5 — identisch zum Desktop). */
  const compareRows = window.MOCK_COMPARE_ROWS || [];
  const locations = window.MOCK_LOCATIONS || [];
  const hochkoenig = ["loc-07", "loc-08", "loc-09", "loc-10"];
  const shortName = (id) => {
    const l = locations.find(x => x.id === id);
    if (!l) return id;
    const p = l.name.split("/");
    return (p.length > 1 ? p[p.length - 1] : l.name).trim();
  };
  const subjectsFor = (m) => {
    let raw = [];
    if (context === "vergleich" && m.field) {
      raw = hochkoenig.map(id => { const row = compareRows.find(r => r.id === id) || {}; return { label: shortName(id), value: row[m.field] }; });
    } else if (m.samples) { raw = m.samples; }
    return raw.map(s => ({ ...s, inside: corridorInside(s.value, m.min, m.max) }));
  };

  const notifyN = rows.filter(r => r.notify).length;
  const markN   = rows.filter(r => r.mark).length;

  return (
    <ScreenScroll padding={14}>
      <Eyebrow style={{ marginBottom: 4 }}>{ctx.eyebrow}{profileLabel ? ` · ${profileLabel}` : ""}</Eyebrow>
      <div style={{ fontSize: 19, fontWeight: 600, letterSpacing: "-0.01em", lineHeight: 1.2, marginBottom: 6 }}>{ctx.title}</div>
      <div style={{ fontSize: 13, color: "var(--g-ink-2)", lineHeight: 1.5, marginBottom: 14 }}>{ctx.lead}</div>

      {/* Legende */}
      <div style={{ display: "flex", flexDirection: "column", gap: 8, padding: "12px 14px", marginBottom: 14, background: "var(--g-card-alt)", border: "1px solid var(--g-rule-soft)", borderRadius: "var(--g-r-3)" }}>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 9, fontSize: 12.5, color: "var(--g-ink-2)" }}>
          <span style={{ width: 24, height: 9, borderRadius: 4, background: "var(--g-good)", opacity: 0.85, flexShrink: 0 }}/>
          im Bereich = <strong style={{ color: "var(--g-good)" }}>markiert</strong>
        </span>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 9, fontSize: 12.5, color: "var(--g-ink-2)" }}>
          <span style={{ width: 24, height: 9, borderRadius: 4, background: "rgba(192,138,26,0.28)", flexShrink: 0 }}/>
          außerhalb = <strong style={{ color: "#8a6210" }}>Warnung</strong>
        </span>
      </div>

      {/* Cards */}
      {rows.map(m => (
        <CM_Card key={m.id} metric={m} subjects={subjectsFor(m)} onChange={(patch) => patchRow(m.id, patch)} onRemove={() => removeRow(m.id)}/>
      ))}

      {/* Metrik hinzufügen */}
      {poolLeft.length > 0 && (
        <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 4, marginBottom: 6 }}>
          <div className="mono" style={{ fontSize: 10, color: "var(--g-ink-4)", letterSpacing: "0.08em", textTransform: "uppercase" }}>Metrik hinzufügen</div>
          {poolLeft.map(m => (
            <MBtn key={m.id} block variant="ghost" size="lg" onClick={() => addRow(m)}>＋ {m.label}</MBtn>
          ))}
        </div>
      )}

      {/* Zusammenfassung */}
      <div style={{ display: "flex", alignItems: "center", gap: 16, marginTop: 10, flexWrap: "wrap" }}>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 7, fontSize: 12.5, color: "var(--g-ink-2)" }}><Dot tone="warn"/> {notifyN} × Warnen</span>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 7, fontSize: 12.5, color: "var(--g-ink-2)" }}><Dot tone="good"/> {markN} × Markieren</span>
      </div>
      {ctx.neutral && (
        <div className="mono" style={{ fontSize: 10.5, color: "var(--g-ink-4)", marginTop: 8, letterSpacing: "0.02em", lineHeight: 1.5 }}>
          kein Score · kein Rang · Wertebereiche markieren nur, sie sortieren nicht
        </div>
      )}
      {footer && <div style={{ marginTop: 22, paddingTop: 18, borderTop: "1px solid var(--g-rule-soft)" }}>{footer}</div>}
    </ScreenScroll>
  );
}

/* ════════════════════ CompareEndDateControlMobile — Laufzeit (E8/C3) ════════════════════ */
function CompareEndDateControlMobile({ value, onChange }) {
  const [mode, setMode] = React.useState(value ? "date" : "open");
  const [date, setDate] = React.useState(value || "2026-04-30");
  const wd = (typeof stageWeekdayDE === "function" && date) ? stageWeekdayDE(date) : null;
  const pick = (m) => { setMode(m); onChange && onChange(m === "date" ? date : null); };

  const Opt = ({ id, title, sub }) => {
    const on = mode === id;
    return (
      <button onClick={() => pick(id)} style={{
        width: "100%", textAlign: "left", cursor: "pointer", minHeight: 56,
        padding: "14px 14px", borderRadius: "var(--g-r-3)", marginBottom: 8,
        background: on ? "var(--g-accent-tint)" : "var(--g-card)",
        border: on ? "1.5px solid var(--g-accent)" : "1px solid var(--g-rule)",
        fontFamily: "var(--g-font-sans)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ width: 18, height: 18, borderRadius: "50%", flexShrink: 0, border: `1.5px solid ${on ? "var(--g-accent)" : "var(--g-rule)"}`, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>
            {on && <span style={{ width: 9, height: 9, borderRadius: "50%", background: "var(--g-accent)" }}/>}
          </span>
          <span style={{ fontSize: 15, fontWeight: 600, color: on ? "var(--g-accent-deep)" : "var(--g-ink)" }}>{title}</span>
        </div>
        <div style={{ fontSize: 12.5, color: "var(--g-ink-3)", lineHeight: 1.5, marginTop: 6, paddingLeft: 28 }}>{sub}</div>
      </button>
    );
  };

  return (
    <div style={{ fontFamily: "var(--g-font-sans)" }}>
      <div className="mono" style={{ fontSize: 10, color: "var(--g-ink-4)", letterSpacing: "0.10em", textTransform: "uppercase", marginBottom: 10 }}>Laufzeit</div>
      <Opt id="open" title="Bis auf Weiteres" sub="Läuft, bis du pausierst."/>
      <Opt id="date" title="Bis Datum" sub="Zum Saisonende automatisch pausieren — kein Löschen."/>
      {mode === "date" && (
        <label style={{ display: "flex", alignItems: "center", gap: 10, background: "var(--g-card)", border: "1px solid var(--g-rule)", borderRadius: "var(--g-r-3)", padding: "0 12px", minHeight: 52, cursor: "pointer", marginTop: 2 }}>
          {wd && <span className="mono" style={{ fontSize: 12, fontWeight: 700, color: "var(--g-accent-deep)", background: "var(--g-accent-tint)", borderRadius: 3, padding: "4px 8px" }}>{wd}</span>}
          <input type="date" value={date} onChange={e => { setDate(e.target.value); onChange && onChange(e.target.value); }} className="mono"
            style={{ flex: 1, border: "none", outline: "none", background: "transparent", fontFamily: "var(--g-font-mono)", fontSize: 16, color: "var(--g-ink)", fontVariantNumeric: "tabular-nums", minHeight: 44 }}/>
        </label>
      )}
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 12, fontSize: 12.5, color: "var(--g-ink-2)", lineHeight: 1.5 }}>
        <span style={{ width: 7, height: 7, borderRadius: "50%", background: mode === "date" ? "var(--g-warn)" : "var(--g-good)", flexShrink: 0 }}/>
        {mode === "date" ? "Danach Auto-Pause — erscheint pausiert im Hub, kein Datenverlust." : "Stehender Monitor — kein automatisches Ende."}
      </div>
    </div>
  );
}

/* ─── Export ─── */
Object.assign(window, {
  CM_Band, CM_Bound, CM_Effect, CM_PreviewChips, CM_Card,
  CorridorEditorMobile, CompareEndDateControlMobile,
});
